<!-- Include header information -->
<?php require_once( ROOT_PATH . '/includes/header.php') ?>
<!-- Include navbar -->
<?php require_once(ROOT_PATH . '/includes/navbar.php'); ?>
<!-- Get class -->
<?php $thisClass = getSingleClass($conn, $class); ?>

<!DOCTYPE html>
<html>
<head>
    <style>
        table{
        }
        th{
            text-align: left;
            border-bottom: 1px solid black;
        }
        tr{
            text-align:left;
        }
        tr:nth-child(odd){
            background-color: #eeee;
        }
        tr:first-child{
            background: #ffff;
        }
    </style>
</head>

<body>
	<!-- container - wraps whole page -->
	<div class="container">
        <hr>
        <div class="container-fluid">
            <title>Pathfinder | <?php echo $thisClass['name']?></title>
            <h1><?php echo $thisClass['name']?></h1>
            <p><?php echo $thisClass['description']?></p>
            <p><b>Role: </b><?php echo $thisClass['role']?></p>
            <p><b>Alignment: </b><?php echo $thisClass['alignment']?></p>
            <p><b>Hit die: </b><?php echo $thisClass['hit_die']?></p>
        </div>
        <div class="container-fluid">
            <h4 style="text-align:center;"><b>Table: <?php echo $thisClass['name']?></b></h4>
            <table style="width:80%;margin:auto">
            <tr>
                <th>Level</th>
                <th>Base Attack</th>
                <th>Fort Save</th>
                <th>Reflex Save</th>
                <th>Will Save</th>
            </tr>
            <!-- class fetch -->
            <?php
            // $thisClass = getSingleClass($conn, $class);
            for ($i=0; $i < 20; $i++) { 
                echo '<tr>';
                if($i+1 == 2){
                    echo     '<td>'. ($i+1) .'nd</td>';
                }
                else if($i+1 == 3){
                    echo     '<td>'. ($i+1) .'rd</td>';
                } else {
                    echo     '<td>'. ($i+1) .'th</td>';
                }
                if($thisClass['base_attack_bonus']){
                    echo    '<td>+'.($i+1).'</td>';
                }
                if($thisClass['fort'] == 'good'){
                    echo    '<td>+'.floor((($i+1)/2)+2).'</td>';
                }else{
                    echo    '<td>+'.abs((ceil(($i-1)/3))).'</td>';
                }
                if($thisClass['dex'] == 'good'){
                    echo    '<td>+'.floor((($i+1)/2)+2).'</td>';
                }else{
                    echo    '<td>+'.abs((ceil(($i-1)/3))).'</td>';

                }
                if($thisClass['wis'] == 'good'){
                    echo    '<td>+'.floor((($i+1)/2)+2).'</td>';
                }else{
                    echo    '<td>+'.abs((ceil(($i-1)/3))).'</td>';

                }
                echo '</tr>';
            }
            ?>
            <!-- // class fetch -->
            </table> 
        </div>
		<!-- Footer -->
		<?php require_once( ROOT_PATH . '/includes/footer.php') ?>
		<!-- // Footer -->
	</div>
	<!-- // Page content -->		
</body>
</html>