<!-- Include header information -->
<?php require_once( ROOT_PATH . '/includes/header.php') ?>
<!-- Include navbar -->
<?php require_once(ROOT_PATH . '/includes/navbar.php'); ?>
<!DOCTYPE html>
<html>
<head>
	<title>Pathfinder | Create Post</title>
</head>
<body>
	<!-- container - wraps whole page -->
	<div class="container">
		<hr>
		<div class="content">
			<form action="/" class="create-post" name="create-post">
                <input style="border-radius:5px;" type="text" name="post-title" value="Title...">
                <textarea style="border-radius:5px;display:block;margin-top:15px;height:200px;width:400px" name="post-body" form="create-post">Post body...</textarea>
                <input style="margin-top:15px;" type="file" name="post-image" class="post-image">
                <hr style="width:50%; margin-left:0">
                <button type="submit" name="post-btn">Create</button>
            </form>
		</div>
		<!-- Footer -->
		<?php require_once( ROOT_PATH . '/includes/footer.php') ?>
		<!-- // Footer -->
	</div>
	<!-- // Page content -->		
</body>
</html>